### ISSUE TITLE
rerun with MDAnalysis 2.4

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/RDKitConverter-benchmark#4]
@cbouy is it worthwhile to rerun with MDA 2.4 — did anything important change in the rdkit converter?

cc: @IAlibay

**Comment by IAlibay** [comment]
No major changes to the converter but py3.11 might have sped things up?

**Comment by orbeckst** [comment]
I don’t think that speed was recorded or at least not reported. This was about accuracy. 

If there is not likely any change then rerunning doesn’t have high priority. 

IIRC, @cbouy ran these calculations on one of my workstations so I should be able to do it, come to think. But if it’s not urgent then it’ll sit for a while… until someone says they need it for a presentation or something.  ;-)

**Comment by IAlibay** [comment]
Ah ok, yeah I can't think of anything that changed in core since we ran the benchmarks. Mayyybee upstream changes in rdkit?

**Comment by cbouy** [comment]
Nope no changes that I'm aware of!

And there was supposed to be the timing recorded in there but it didn't work as the benchmarking encountered some weird molecule that made it crash. It should be fixed for the next run though.

Speaking of upstream RDKit changes, there's the RunReactantInPlace which is supposed to work much faster than creating a new mol and transferring the properties on each atom from one mol to the other, which was one of the bottlenecks IIRC. Hopefully I can find some time this year!

**Comment by IAlibay** [comment]
@cbouy would you be ok raising an issue about it on the core library?
